FROM eclipse-temurin:17-jdk-jammy

RUN addgroup --system spring && adduser --system --ingroup spring spring
USER spring

WORKDIR /app

COPY target/user-management-system-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
